### ISSUE TITLE
Invalid syntax in the latest repo

### ISSUE THREAD

**Issue by swsychen** [danijar/dreamerv3#115]
Hi, when I tried to run the example.py with the latest repo, I ran into this issue:

Traceback (most recent call last):
  File "/home/chenc/dreamerv3_new/example.py", line 4, in <module>
    import dreamerv3
  File "/home/chenc/dreamerv3_new/dreamerv3/__init__.py", line 1, in <module>
    from .agent import Agent
  File "/home/chenc/dreamerv3_new/dreamerv3/agent.py", line 4, in <module>
    import embodied
  File "/home/chenc/dreamerv3_new/embodied/__init__.py", line 7, in <module>
    from . import replay
  File "/home/chenc/dreamerv3_new/embodied/replay/__init__.py", line 1, in <module>
    from .replay import Replay
  File "/home/chenc/dreamerv3_new/embodied/replay/replay.py", line 12, in <module>
    from . import selectors
  File "/home/chenc/dreamerv3_new/embodied/replay/selectors.py", line 88
    segment = prob[*path]
                        ^
SyntaxError: invalid syntax

Could someone help me with this issue? I would be very grateful.

**Comment by danijar** [comment]
What's your Python version? Can you try running with a newer version?

**Comment by swsychen** [comment]
I just installed Python 3.11. And everything looks fine with the new version now. Thanks
