### ISSUE TITLE
BrokenPipeError using Parallel class

### ISSUE THREAD

**Issue by joeagriffith** [danijar/dreamerv3#49]
Attempting to use the Parallel class to run gym-like environments in parallel.
Training runs successfully with <5 instances, however crashes with a BrokenPipeError mid-training when num_instances > ~10. 

Do you have any ideas what would cause this type of error?

===========================ENV WRAPPING CODE (after gym.make)=======================
def make_batched_parallel_env(envs, manager:ComputeManager, config):
    
    envs = map(lambda e: from_gym.FromGym(e, obs_key='vector'), envs)
    envs = map(lambda e: dreamerv3.wrap_env(e, config), envs)

    if config.envs.parallel != 'none':
        envs = map(lambda e: partial(embodied.Parallel, lambda: e, config.envs.parallel), envs)
    else:
        raise("Invalid parallel type for config.envs.parallel")
    if config.envs.restart:
        envs = map(lambda e: partial(wrappers.RestartOnException, e), envs)
    
    envs = [e() for e in envs]

    return embodied.BatchEnv(envs, parallel=config.envs.parallel != 'none')

def prepare_for_dreamer(envs, manager:ComputeManager, config:embodied.Config, parallel:bool):
    
    env = make_batched_parallel_env(envs, manager, config)
    step = embodied.Counter()
    logger = embodied.Logger(step, [
        embodied.logger.TerminalOutput(),
        embodied.logger.JSONLOutput(config.logdir+'/metrics', 'metrics.jsonl'),
        embodied.logger.TensorBoardOutput(config.logdir+'tensorboard'),
    ])

    agent = dreamerv3.Agent(env.obs_space, env.act_space, step, config)

    replay = embodied.replay.Uniform(
        config.batch_length, config.replay_size, config.logdir+'/replay'
    )

    args = embodied.Config(
        **config.run,
        logdir=config.logdir,
        batch_steps=config.batch_size * config.batch_length,
    )

    return agent, env, replay, logger, args

=======================================ERROR MESSAGE================
Error inside process worker: Traceback (most recent call last):
  File "/home/joeag/Documents/Group-Project/jax-venv/lib/python3.8/site-packages/dreamerv3/embodied/core/worker.py", line 195, in _loop
    message, callid, payload = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by joeagriffith** [comment]
Issue was memory leak in our environment.

**Comment by joeagriffith** [comment]
Issue was a  memory leak in our env.
